/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pengaturan;

import MainMenu.F_Menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Daulah
 */

public class F_UbahPassword extends javax.swing.JFrame {

    public static String temp_id_pengguna = "", temp_username = "";

    /**
     * Creates new form F_UbahPassword
     */
    public F_UbahPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        setLocationRelativeTo(this);
        username.setText(temp_username);
        password_lama.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        password_baru = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password_lama = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        konfirmasi_password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Password Baru");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        password_baru.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_baru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        password_baru.setMargin(new java.awt.Insets(0, 3, 0, 3));
        password_baru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_baruKeyTyped(evt);
            }
        });
        getContentPane().add(password_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 170, 250, 30));

        username.setEditable(false);
        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        username.setMargin(new java.awt.Insets(0, 3, 0, 3));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 98, 250, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password Lama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 142, -1, -1));

        password_lama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_lama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        password_lama.setMargin(new java.awt.Insets(0, 3, 0, 3));
        password_lama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_lamaKeyTyped(evt);
            }
        });
        getContentPane().add(password_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 134, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Konfirmasi");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        konfirmasi_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        konfirmasi_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        konfirmasi_password.setMargin(new java.awt.Insets(0, 3, 0, 3));
        konfirmasi_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasi_passwordActionPerformed(evt);
            }
        });
        konfirmasi_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                konfirmasi_passwordKeyTyped(evt);
            }
        });
        getContentPane().add(konfirmasi_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 206, 250, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 177, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 104, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 142, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText(":");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 213, -1, -1));

        simpan.setText("Simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.setIconTextGap(1);
        simpan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 242, 87, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UBAH PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 11, 70, 64));

        keluar.setText("Kembali");
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setIconTextGap(1);
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 242, 87, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Ubah PW.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_baruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_baruKeyTyped
        String batas = String.valueOf(password_baru.getPassword());
        if (batas.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Input Maksimal 20 Karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_password_baruKeyTyped

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        String batas = username.getText();
        if (batas.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Input Maksimal 20 Karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void password_lamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_lamaKeyTyped
        String batas = String.valueOf(password_lama.getPassword());
        if (batas.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Input Maksimal 20 Karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_password_lamaKeyTyped

    private void konfirmasi_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasi_passwordActionPerformed
        simpanActionPerformed(evt);
    }//GEN-LAST:event_konfirmasi_passwordActionPerformed

    private void konfirmasi_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konfirmasi_passwordKeyTyped
        String batas = String.valueOf(konfirmasi_password.getPassword());
        if (batas.length() >= 20) {
            JOptionPane.showMessageDialog(this, "Input Maksimal 20 Karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_konfirmasi_passwordKeyTyped

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String newPassword = String.valueOf(password_baru.getPassword()).trim();
        String confirmPassword = String.valueOf(konfirmasi_password.getPassword()).trim();
        String oldPassword = String.valueOf(password_lama.getPassword()).trim();

        if (newPassword.isEmpty() || confirmPassword.isEmpty() || oldPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua Kolom Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Konfirmasi Password Baru Salah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection koneksi = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_rsprabu", "root", "");

            String query = "SELECT * FROM user_pengguna WHERE id_pengguna = ? AND username = ? AND password = ?";
            try (PreparedStatement ps = koneksi.prepareStatement(query)) {
                ps.setString(1, temp_id_pengguna);
                ps.setString(2, temp_username);
                ps.setString(3, oldPassword);

                ResultSet re = ps.executeQuery();
                if (re.next()) {
                    String updateQuery = "UPDATE user_pengguna SET password = ? WHERE id_pengguna = ?";
                    try (PreparedStatement psUpdate = koneksi.prepareStatement(updateQuery)) {
                        psUpdate.setString(1, newPassword);
                        psUpdate.setString(2, temp_id_pengguna);
                        psUpdate.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password Salah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + ex.getMessage());
        } finally {
            if (koneksi != null) {
                try {
                    koneksi.close();
                } catch (SQLException ex) {
                }
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        F_Menu fb = new F_Menu();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_keluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(30);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_UbahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_UbahPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton keluar;
    private javax.swing.JPasswordField konfirmasi_password;
    private javax.swing.JPasswordField password_baru;
    private javax.swing.JPasswordField password_lama;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
