/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainMenu;

import Cetak.C_Pemeriksaan;
import Cetak.C_RawatInap;
import Cetak.C_RawatJalan;
import Login.F_Login;
import Master.F_Dokter;
import Master.F_Obat;
import Master.F_Pasien;
import Master.F_Pemeriksaan;
import Master.F_Perawat;
import Master.F_Ruangan;
import Pengaturan.F_TambahAdmin;
import Pengaturan.F_UbahPassword;
import Transaksi.F_RawatInap;
import Transaksi.F_RawatJalan;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Daulah
 */

public class F_Menu extends javax.swing.JFrame {

    /**
     * Creates new form F_Menu
     */
    public F_Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        data_pasien = new javax.swing.JMenuItem();
        data_dokter = new javax.swing.JMenuItem();
        data_obat = new javax.swing.JMenuItem();
        perawat = new javax.swing.JMenuItem();
        data_ruangan = new javax.swing.JMenuItem();
        pemeriksaan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rawat_jalan = new javax.swing.JMenuItem();
        rawat_inap = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        laporan_pasien = new javax.swing.JMenuItem();
        laporan_dokter = new javax.swing.JMenuItem();
        laporan_Obat = new javax.swing.JMenuItem();
        laporan_ruangan = new javax.swing.JMenuItem();
        laporan_perawat = new javax.swing.JMenuItem();
        laporan_pemeriksaan = new javax.swing.JMenuItem();
        rawatjalan = new javax.swing.JMenuItem();
        rawatinap = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ubah_password = new javax.swing.JMenuItem();
        tambah_admin = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg menu.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(3278, 32768));
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 550));

        jMenu1.setText("Master");

        data_pasien.setText("Pasien");
        data_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pasienActionPerformed(evt);
            }
        });
        jMenu1.add(data_pasien);

        data_dokter.setText("Dokter");
        data_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_dokterActionPerformed(evt);
            }
        });
        jMenu1.add(data_dokter);

        data_obat.setText("Obat");
        data_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_obatActionPerformed(evt);
            }
        });
        jMenu1.add(data_obat);

        perawat.setText("Perawat");
        perawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perawatActionPerformed(evt);
            }
        });
        jMenu1.add(perawat);

        data_ruangan.setText("Ruangan");
        data_ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_ruanganActionPerformed(evt);
            }
        });
        jMenu1.add(data_ruangan);

        pemeriksaan.setText("Pemeriksaan");
        pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemeriksaanActionPerformed(evt);
            }
        });
        jMenu1.add(pemeriksaan);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaksi");

        rawat_jalan.setText("Rawat Jalan");
        rawat_jalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawat_jalanActionPerformed(evt);
            }
        });
        jMenu3.add(rawat_jalan);

        rawat_inap.setText("Rawat Inap");
        rawat_inap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawat_inapActionPerformed(evt);
            }
        });
        jMenu3.add(rawat_inap);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Laporan");

        laporan_pasien.setText("Laporan Data Pasien");
        laporan_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pasienActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_pasien);

        laporan_dokter.setText("Laporan Data Dokter");
        laporan_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_dokterActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_dokter);

        laporan_Obat.setText("Laporan Data Obat");
        laporan_Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_ObatActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_Obat);

        laporan_ruangan.setText("Laporan Data Ruangan");
        laporan_ruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_ruanganActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_ruangan);

        laporan_perawat.setText("Laporan Data Perawat");
        laporan_perawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_perawatActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_perawat);

        laporan_pemeriksaan.setText("Laporan Hasil Pemeriksaan");
        laporan_pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pemeriksaanActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_pemeriksaan);

        rawatjalan.setText("Nota Rawat Jalan");
        rawatjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatjalanActionPerformed(evt);
            }
        });
        jMenu7.add(rawatjalan);

        rawatinap.setText("Nota Rawat Inap");
        rawatinap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatinapActionPerformed(evt);
            }
        });
        jMenu7.add(rawatinap);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Pengaturan");

        ubah_password.setText("Ubah Password");
        ubah_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_passwordActionPerformed(evt);
            }
        });
        jMenu4.add(ubah_password);

        tambah_admin.setText("Tambah Admin");
        tambah_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_adminActionPerformed(evt);
            }
        });
        jMenu4.add(tambah_admin);

        jMenuBar1.add(jMenu4);

        keluar.setText("Logout");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pasienActionPerformed
        F_Pasien fb = new F_Pasien();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_data_pasienActionPerformed

    private void data_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_dokterActionPerformed
        F_Dokter fb = new F_Dokter();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_data_dokterActionPerformed

    private void data_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_obatActionPerformed
        F_Obat fb = new F_Obat();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_data_obatActionPerformed

    private void perawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perawatActionPerformed
        F_Perawat fb = new F_Perawat();
        fb.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_perawatActionPerformed

    private void data_ruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_ruanganActionPerformed
        F_Ruangan fb = new F_Ruangan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_data_ruanganActionPerformed

    private void pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemeriksaanActionPerformed
        F_Pemeriksaan fb = new F_Pemeriksaan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pemeriksaanActionPerformed

    private void rawat_jalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawat_jalanActionPerformed
        F_RawatJalan fb = new F_RawatJalan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rawat_jalanActionPerformed

    private void rawat_inapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawat_inapActionPerformed
        F_RawatInap fb = new F_RawatInap();
        fb.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_rawat_inapActionPerformed

    private void laporan_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pasienActionPerformed
        try {
            String NamaFile = "src/Laporan/report_pasien.jasper";
            Connection koneksi = Koneksi.Koneksi.getKoneksi();
            HashMap hash = new HashMap();
            File file = new File(NamaFile);

            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Pasien");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak " + e);
        }
    }//GEN-LAST:event_laporan_pasienActionPerformed

    private void laporan_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_dokterActionPerformed
        try {
            String NamaFile = "src/Laporan/report_datadokter.jasper";
            Connection koneksi = Koneksi.Koneksi.getKoneksi();
            HashMap hash = new HashMap();
            File file = new File(NamaFile);

            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Dokter");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak " + e);
        }
    }//GEN-LAST:event_laporan_dokterActionPerformed

    private void laporan_ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_ObatActionPerformed
        try {
            String NamaFile = "src/Laporan/report_dataobat.jasper";
            Connection koneksi = Koneksi.Koneksi.getKoneksi();
            HashMap hash = new HashMap();
            File file = new File(NamaFile);

            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Obat");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak " + e);
        }
    }//GEN-LAST:event_laporan_ObatActionPerformed

    private void laporan_ruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_ruanganActionPerformed
        try {
            String NamaFile = "src/Laporan/report_ruangan.jasper";
            Connection koneksi = Koneksi.Koneksi.getKoneksi();
            HashMap hash = new HashMap();
            File file = new File(NamaFile);

            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Ruangan");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak " + e);
        }
    }//GEN-LAST:event_laporan_ruanganActionPerformed

    private void laporan_perawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_perawatActionPerformed
        try {
            String NamaFile = "src/laporan/report_perawat.jasper";
            Connection koneksi = Koneksi.Koneksi.getKoneksi();
            HashMap hash = new HashMap();
            File file = new File(NamaFile);

            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setTitle("Laporan Data Perawat");
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak " + e);
        }
    }//GEN-LAST:event_laporan_perawatActionPerformed

    private void laporan_pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pemeriksaanActionPerformed
        C_Pemeriksaan fb = new C_Pemeriksaan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_laporan_pemeriksaanActionPerformed

    private void rawatjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatjalanActionPerformed
        C_RawatJalan fb = new C_RawatJalan();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rawatjalanActionPerformed

    private void rawatinapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatinapActionPerformed
        C_RawatInap fb = new C_RawatInap();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rawatinapActionPerformed

    private void ubah_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_passwordActionPerformed
        F_UbahPassword fb = new F_UbahPassword();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ubah_passwordActionPerformed

    private void tambah_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_adminActionPerformed
        F_TambahAdmin fb = new F_TambahAdmin();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tambah_adminActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        int response = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmas",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            F_Login fb = new F_Login();
            fb.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem data_dokter;
    private javax.swing.JMenuItem data_obat;
    private javax.swing.JMenuItem data_pasien;
    private javax.swing.JMenuItem data_ruangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenuItem laporan_Obat;
    private javax.swing.JMenuItem laporan_dokter;
    private javax.swing.JMenuItem laporan_pasien;
    private javax.swing.JMenuItem laporan_pemeriksaan;
    private javax.swing.JMenuItem laporan_perawat;
    private javax.swing.JMenuItem laporan_ruangan;
    private javax.swing.JMenuItem pemeriksaan;
    private javax.swing.JMenuItem perawat;
    private javax.swing.JMenuItem rawat_inap;
    private javax.swing.JMenuItem rawat_jalan;
    private javax.swing.JMenuItem rawatinap;
    private javax.swing.JMenuItem rawatjalan;
    private javax.swing.JMenuItem tambah_admin;
    private javax.swing.JMenuItem ubah_password;
    // End of variables declaration//GEN-END:variables
}
